In [1]:
import numpy as np

In [2]:
import scipy

In [12]:
a = np.array(([1, 2, 3, 4, 5],
              [6, 7, 8, 9, 0]))

In [13]:
a.shape

(2, 5)

In [23]:
a.reshape(1,10)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [14]:
a.astype('float64')


array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [24]:
a.strides


(20, 4)

In [25]:
b = a.reshape(5, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [26]:
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [37]:
np.linspace(0, 1, 5, endpoint = True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
c = np.array(([1, 2, 3, 4, 5],
              [6, 7, 8, 9, 0]))

In [40]:
c ** 3

array([[  1,   8,  27,  64, 125],
       [216, 343, 512, 729,   0]], dtype=int32)

In [41]:
c + 2

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  2]])

In [42]:
2  ** a

array([[  2,   4,   8,  16,  32],
       [ 64, 128, 256, 512,   1]], dtype=int32)

In [46]:
c.sum(axis = 1)

array([15, 30])

In [47]:
c.ravel()[c.argmax()] #Вытягивание массива и нахождение максимума

9

In [59]:
v = np.array([True, False, True, True, False, True])
v.reshape(2,3)


array([[ True, False,  True],
       [ True, False,  True]])

In [55]:
np.logical_not(v)

array([False,  True, False, False,  True, False])

In [51]:
np.any(v)

True

In [52]:
~v

array([False,  True, False, False,  True])

In [65]:
s = np.array([[True, False, True],
             [True, False, True]])
s.all(axis = 0)

array([ True, False,  True])

In [ ]:
s.all(axis = 1) #axis выполняет постро чно 

In [70]:
m = np.array(([100, 2, 3, 4, 5],
              [6, 7, 8, 9, 0]))

In [71]:
np.isclose(m,a)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [85]:
np.random.seed(5511)

b = np.random.randint(5, 7, size=(4, 1))
b

array([[5],
       [5],
       [5],
       [6]])

In [86]:
np.random.seed(1645)

v = np.random.randint(-1, 100, size =(1,4))
v


array([[49, 76, 25,  4]])

In [87]:
b * v

array([[245, 380, 125,  20],
       [245, 380, 125,  20],
       [245, 380, 125,  20],
       [294, 456, 150,  24]])

In [92]:
s = np.random.randint(0, 15, size=(3, 6, 3))
s

array([[[14, 12,  7],
        [ 8,  2,  8],
        [11, 14,  4],
        [ 5, 12,  7],
        [12,  5, 12],
        [11, 11,  3]],

       [[ 8, 12, 10],
        [12,  7,  2],
        [ 5,  7, 13],
        [ 5, 14,  5],
        [ 5,  6, 11],
        [ 7, 12,  2]],

       [[11, 12, 12],
        [ 5,  5, 10],
        [11,  0, 14],
        [13,  1,  4],
        [ 7,  8,  2],
        [13, 10,  7]]])

In [100]:
a = np.array([1, 2, 3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,12])

In [101]:
variants = a[np.logical_not(a % 3)]
variants

array([ 3,  6,  9, 12])

In [107]:
variants = [a[0::],a[:]]
print(*map(repr, variants), sep='\n')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])


In [115]:
a = np.array([[1, 2, 3 ,4 ,5 ,6] ,
              [7 ,8 ,9 ,10 ,12,5]])
(a == 5).any(axis=0)

array([False, False, False, False,  True,  True])

In [117]:
s > 0
np.where(s > 0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int32),
 array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 0, 0, 0, 1,
        1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 0, 0, 0, 1, 1, 1, 2, 2,
        3, 3, 3, 4, 4, 4, 5, 5, 5], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 2,
        0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32))

In [121]:
s[np.ix_([1,2,1], [0,1,1])]

array([[[ 8, 12, 10],
        [12,  7,  2],
        [12,  7,  2]],

       [[11, 12, 12],
        [ 5,  5, 10],
        [ 5,  5, 10]],

       [[ 8, 12, 10],
        [12,  7,  2],
        [12,  7,  2]]])

In [122]:
np.random.permutation(20)

array([19,  4,  0,  8,  7,  3,  6, 13, 11,  5, 18,  9, 17, 14, 15,  2, 12,
       16, 10,  1])

In [137]:
s = np.sort(np.random.choice(40, size=(3,10)).ravel())
print(*map( repr ,s), sep = '\n' )
np.unique(s)

0
2
3
7
8
9
9
13
14
14
15
16
17
19
19
20
20
23
26
27
27
27
29
30
32
35
35
36
36
37


array([ 0,  2,  3,  7,  8,  9, 13, 14, 15, 16, 17, 19, 20, 23, 26, 27, 29,
       30, 32, 35, 36, 37])

In [ ]:
# np.vstack((a, b), axis=0) обьединение массивов во вертикали

In [138]:
# np.hstack((a, b), axis=0) обьединение массивов по горизонтали

In [ ]:
d = pdist(X) #squareform(d) 